apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: autonomouspen/scanner:latest
        ports:
        - containerPort: 8080
